### ISSUE TITLE
TMC Cancela TFK200 lua error

### ISSUE THREAD

**Issue by IhanaMies** [oschuhm/FS22_ToolDisplay#5]
This forestry equipment causes lua error:
Error: Running LUA method 'loadSharedI3DFileAsyncFinished'

2023-08-24 19:27 data/vehicles/tmcCancela/tfk200/tfk200.i3d (5.34 ms)
2023-08-24 19:27 data/shared/assets/powerTakeOffs/walterscheidW.i3d (0.89 ms)
2023-08-24 19:27 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
dataS/scripts/i3d/I3DUtil.lua(52) : bad argument #1 to 'find' (string expected, got table)

I believe this equipment is part of the base game. I'm not 100% sure.

I tested it by creating new game with only this mod active and buying said equipment from the store.
Having dev console enable it opened up on this error.

**Comment by IhanaMies** [comment]
Paladin Stump Grinder also causes that error.

**Comment by oschuhm** [comment]
stump cutters are excluded for ToDi in version 0.0.0.5
will check is they can be included in future versions again.
